### ISSUE TITLE
Also publish this as a library

### ISSUE THREAD

**Issue by cobexer** [buraksezer/olric-cloud-plugin#1]
I did some research and it appears to be really hard to use go plugins in a go application if the application uses any of the same packages the plugin uses.

As far as I understand I have to use the exact same version of the kubernetes go client library in my application that was used by this olric-cloud-plugin.

The only way to make sure that happens, as far as I understand, is to use this plugin as a library and thus build it with the same go build.

**Comment by tliron** [comment]
It is indeed painful. I'm getting errors like these:
```
failed to open plugin: plugin.Open("/usr/lib64/olric-cloud-plugin"): plugin was built with a different version of package github.com/mitchellh/go-homedir
```

**Comment by buraksezer** [comment]
> As far as I understand I have to use the exact same version of the kubernetes go client library in my application that was used by this olric-cloud-plugin.

Yes it is. This is how Go plugins works. 

Service discovery plugins are actually designed as a library. See this:

```go
import "github.com/buraksezer/olric-cloud-plugin/lib"
c := olric.New("lan")
...
cd := &lib.CloudDiscovery{}
labelSelector := fmt.Sprintf("app.kubernetes.io/name=%s,app.kubernetes.io/instance=%s", name, instance)
c.ServiceDiscovery = map[string]interface{}{
  "plugin":   cd,
  "provider": "k8s",
  "args":     fmt.Sprintf("namespace=%s label_selector=\"%s\"", namespace, labelSelector),
}
```

Here is another sample: https://github.com/pilillo/igovium/blob/master/cache/olric_dm.go#L36

**Comment by tliron** [comment]
This is a problematic implementation. I embed Olric in my application and many dependencies do not match versions. I cannot get this plugin to work.

**Comment by buraksezer** [comment]
There is no problem in the implementation. [go-discover](https://github.com/hashicorp/go-discover) imports tons of the libraries. If there are collisions (Kubernetes has this problem), you should fix that problem in your codebase.

**Comment by tliron** [comment]
Thank you. This is not the right project for my company. I wish you the best of luck.
