### ISSUE TITLE
Is it possible to use k8s discovery without an external plugin?

### ISSUE THREAD

**Issue by graveland** [buraksezer/olric-cloud-plugin#2]
Using embedded olric in a service being deployed in k8s, and including this discovery would be great, but managing the build and deployment that includes a plugin is a pain. Importing a discovery package should be easier than building and including a standalone binary?

**Comment by buraksezer** [comment]
Hi @graveland 

I'm so sorry for the late response. This plugin utilizes [hashicorp/go-discover](https://github.com/hashicorp/go-discover) for discovery on Kubernetes and other platforms. Unfortunately, it has too many dependencies and I don't want to import it in the core Olric packages. This is why I decided to build a simple plugin interface. 

You can import and use the plugin package in your own project. I had shared the following snippet in README.md

```go
c := olric.New("lan")
...
cd := &discovery.CloudDiscovery{}
labelSelector := fmt.Sprintf("app.kubernetes.io/name=%s,app.kubernetes.io/instance=%s", name, instance)
c.ServiceDiscovery = map[string]interface{}{
  "plugin":   cd,
  "provider": "k8s",
  "args":     fmt.Sprintf("namespace=%s label_selector=\"%s\"", namespace, labelSelector),
}
``` 

By this way, you can build a standalone binary includes Olric, the plugin and your business logic. You probably don't want to import this huge plugin in your project. Is that right?

**Comment by graveland** [comment]
Thanks for the example!

I definitely understand why you don't want to include it in core, I didn't want to have to build and distribute two binaries and a configuration file in an image when utilising embedded olric, so as long as I can combine k8s discovery with embedded then in happy.
